[package]
name = "razorback_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.29"
syn = { version = "2.0.23", features = ["fold", "full", "extra-traits"] }
