[package]
name = "razorback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2.0.4"
pest = "2.7.7"
pest_derive = "2.7.7"
rand = "0.8.5"
razorback_derive = { path = "../razorback_derive" }
thiserror = "1.0.56"
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]